# Set script parameters from runbook data bus and Orchestrator global variables
# Define any inputs here and then add to the $argsArray and script block parameters below 

Send-MailMessage -To Mikeruddell@tfl.gov.uk -Cc ImtiazAyub@tfl.gov.uk -From mikeruddell@tfl.gov.uk -subject "TEST EMAIL LINE 1" -SmtpServer internalemail.seg.tfl.gov.uk

$DataBusInput0 = "\`d.T.~Vb/{E0CE9640-35DC-4A14-BBBD-2C8F4E50B77E}\`d.T.~Vb/" #Pass ActiveRoles Server FQDN"
$DataBusInput1 = "\`d.T.~Vb/{A0F07C66-55A6-475F-86B4-EC669FF8BC3D}\`d.T.~Vb/" #Pass Domain Name to Work On
$DataBusInput2 = "\`d.T.~Ed/{EF41E46D-9DA2-454F-B51F-1D1E18DEDE77}.Output text\`d.T.~Ed/" #Pass Username
$DataBusInput3 = "\`d.T.~Ed/{421F3881-E64C-4B9D-9617-AE644AC062A6}.Output text\`d.T.~Ed/" #Pass Date to ExtendAccount
$DataBusInput4 = "\`d.T.~Ed/{36EF6A58-2BFD-45A5-B677-C3A49DB8BDC2}.SRID\`d.T.~Ed/" #Pass SRID (REQ NO) to Stamp Custom Attribute

#-----------------------------------------------------------------------

Send-MailMessage -To Mikeruddell@tfl.gov.uk -Cc ImtiazAyub@tfl.gov.uk -From mikeruddell@tfl.gov.uk -subject "TEST EMAIL LINE 2" -SmtpServer internalemail.seg.tfl.gov.uk

## Initialize result and trace variables
# $ResultStatus provides basic success/failed indicator
# $ErrorMessage captures any error text generated by script
# $Trace is used to record a running log of actions
$ResultStatus = ""
$ErrorMessage = ""
$Trace = (Get-Date).ToString() + "`t" + "Runbook activity script started" + " `r`n"

Send-MailMessage -To Mikeruddell@tfl.gov.uk -Cc ImtiazAyub@tfl.gov.uk -From mikeruddell@tfl.gov.uk -subject "TEST EMAIL LINE 3" -SmtpServer internalemail.seg.tfl.gov.uk
       
# Create argument array for passing data bus inputs to the external script session
$argsArray = @()
$argsArray += $DataBusInput0
$argsArray += $DataBusInput1
$argsArray += $DataBusInput2
$argsArray += $DataBusInput3
$argsArray += $DataBusInput4


Send-MailMessage -To Mikeruddell@tfl.gov.uk -Cc ImtiazAyub@tfl.gov.uk -From mikeruddell@tfl.gov.uk -subject "TEST EMAIL LINE 4" -SmtpServer internalemail.seg.tfl.gov.uk

# Establish an external session (to localhost) to ensure 64bit PowerShell runtime using the latest version of PowerShell installed on the runbook server
# Use this session to perform all work to ensure latest PowerShell features and behavior available
$Session = New-PSSession -ComputerName localhost


Send-MailMessage -To Mikeruddell@tfl.gov.uk -Cc ImtiazAyub@tfl.gov.uk -From mikeruddell@tfl.gov.uk -subject "TEST EMAIL LINE 5" -SmtpServer internalemail.seg.tfl.gov.uk

# Invoke-Command used to start the script in the external session. Variables returned by script are then stored in the $ReturnArray variable
$ReturnArray = Invoke-Command -Session $Session -Argumentlist $argsArray -ScriptBlock {
    # Define a parameter to accept each data bus input value. Recommend matching names of parameters and data bus input variables above
    Param(
        [ValidateNotNullOrEmpty()]
        [string]$DataBusInput0,
        
        [ValidateNotNullOrEmpty()]
        [string]$DataBusInput1,

        [ValidateNotNullOrEmpty()]
        [string]$DataBusInput2,

        [ValidateNotNullOrEmpty()]
        [string]$DataBusInput3,

        [ValidateNotNullOrEmpty()]
        [string]$DataBusInput4
    )


Send-MailMessage -To Mikeruddell@tfl.gov.uk -Cc ImtiazAyub@tfl.gov.uk -From mikeruddell@tfl.gov.uk -subject "TEST EMAIL LINE 6" -SmtpServer internalemail.seg.tfl.gov.uk

    # Define function to add entry to trace log variable
    function AppendLog ([string]$Message)
    {
        $script:CurrentAction = $Message
        $script:TraceLog += ((Get-Date).ToString() + "`t" + $Message + " `r`n")
    }


Send-MailMessage -To Mikeruddell@tfl.gov.uk -Cc ImtiazAyub@tfl.gov.uk -From mikeruddell@tfl.gov.uk -subject "TEST EMAIL LINE 7" -SmtpServer internalemail.seg.tfl.gov.uk

    # Set external session trace and status variables to defaults
    $ResultStatus = ""
    $ErrorMessage = ""
    $script:CurrentAction = ""
    $script:TraceLog = ""

    try 
    {
        # Add startup details to trace log
        AppendLog "Script now executing in external PowerShell version [$($PSVersionTable.PSVersion.ToString())] session in a [$([IntPtr]::Size * 8)] bit process"
        AppendLog "Running as user [$([Environment]::UserDomainName)\$([Environment]::UserName)] on host [$($env:COMPUTERNAME)]"
        AppendLog "Parameter values received: DatabusInput0=[$DataBusInput0]; DataBusInput1=[$DataBusInput1]; DataBusInput2=[$DataBusInput2]; DataBusInput3=[$DataBusInput3]; DataBusInput4=[$DataBusInput4]"

        # # # # # # # # # # # # # # # # # # #
        # UPDATE EXPIRY DATE ON ACCOUNT...  #
        # See AppendLog for Comments        #
        # # # # # # # # # # # # # # # # # # #

            AppendLog "Loading Quest Powershell Module"
        Add-PSSnapin Quest.ActiveRoles.ADManagement
            AppendLog "Module Load Command Completed"
       

            AppendLog "Connecting to ActiveRoles Server $DataBusInput0"
        Connect-QADService -Proxy -Service $DataBusInput0 -WarningAction Stop | Out-Null
            AppendLog "ARS Connection Command Completed"

            AppendLog "Pulling Current Expiry Date for $DataBusInput1\$DataBusInput2"
        $AccountExpires=Get-QADUser $DataBusInput1\$DataBusInput2 | select -expandproperty accountexpires
        If($AccountExpires -eq $null){$PreviousExpiry="Permanent/No expiry date set"} else {$PreviousExpiry=$AccountExpires}
            AppendLog "Success - Expiry Date is: $PreviousExpiry"

           AppendLog "Setting Expiry on Account $DataBusInput1\$DataBusInput2 as $DataBusInput3 23:59"
        Set-QADUser "$DataBusInput1\$DataBusInput2" -AccountExpires "$DataBusInput3 23:59" -WarningAction Stop | Out-Null
            AppendLog "Set Expiry Command Completed"

            AppendLog "Pulling Latest Expiry Date for $DataBusInput1\$DataBusInput2"
        $NewExpiry=Get-QADUser $DataBusInput1\$DataBusInput2 | select -expandproperty accountexpires
            AppendLog "Success - Expiry Date is: $NewExpiry"

            AppendLog "Stamping Custom Attribute edsva-TfL-SRAUTO-LastREQ on Account $DataBusInput1\$DataBusInput2 as $DataBusInput4"
        Set-QADUser "$DataBusInput1\$DataBusInput2" -ObjectAttributes @{'edsva-TfL-SRAUTO-LastREQ'="$DatabusInput4"} -WarningAction Stop | Out-Null
            AppendLog "Stamp Custom Attribute Completed"
                                 
       
        # Validate results and set return status
        AppendLog "Finished work, determining result"
        $EverythingWorked = $true
        if($EverythingWorked -eq $true)
        {
           $ResultStatus = "Success"
        }
        else
        {
            $ResultStatus = "Failed"
        }
    }
    catch
    {
        # Catch any errors thrown above here, setting the result status and recording the error message to return to the activity for data bus publishing
        $ResultStatus = "Failed"
        $ErrorMessage = $error[0].Exception.Message
        AppendLog "Exception caught during action [$script:CurrentAction]: $ErrorMessage"
    }
    finally
    {
        # Always do whatever is in the finally block. In this case, adding some additional detail about the outcome to the trace log for return
        if($ErrorMessage.Length -gt 0)
        {
            AppendLog "Exiting external session with result [$ResultStatus] and error message [$ErrorMessage]"
        }
        else
        {
            AppendLog "Exiting external session with result [$ResultStatus]"
        }
        
    }

    # Return an array of the results. Additional variables like "myCustomVariable" can be returned by adding them onto the array
    $resultArray = @()
    $resultArray += $ResultStatus
    $resultArray += $ErrorMessage
    $resultArray += $script:TraceLog
    $resultArray+=$PreviousExpiry
    $resultArray+=$NewExpiry
    return  $resultArray  
     
}#End Invoke-Command

# Get the values returned from script session for publishing to data bus
$ResultStatus = $ReturnArray[0]
$ErrorMessage = $ReturnArray[1]
$Trace += $ReturnArray[2]
$PreviousExpiry = $ReturnArray[3]
$NewExpiry = $ReturnArray[4]

# Record end of activity script process
$Trace += (Get-Date).ToString() + "`t" + "Script finished" + " `r`n"

# Close the external session
Remove-PSSession $Session