#========================================================================
# Created with: SAPIEN Technologies, Inc., PowerShell Studio 2012 v3.1.35
# Created on:   1/14/2016 2:23 PM
# Created by:   xdanielhobbs
# Organization: DTKEITINNOVATIONS
# Filename:     
#========================================================================


# Set script parameters from runbook data bus and Orchestrator global variables
# Define any inputs here and then add to the $argsArray and script block parameters below 


$DataBusInput0 = "\`d.T.~Vb/{7E698CF9-1B50-446E-91F7-97B628F1391F}\`d.T.~Vb/" #Pass ActiveRoles Server FQDN"
$DataBusInput1 = "\`d.T.~Vb/{7C9EF396-A036-4E8B-8C99-708CD821BF19}\`d.T.~Vb/" #Pass Domain Name to Work On
$DataBusInput2 = "\`d.T.~Ed/{F534A874-451B-45E6-A508-532A79B27EF3}.Output text\`d.T.~Ed/" #Pass Username
$DataBusInput3 = "\`d.T.~Ed/{1D1FAE05-3DAA-4C2E-9BCD-68783FB68A97}.SRID\`d.T.~Ed/" #Pass Remedy Request Number
$DataBusInput4 = "\`d.T.~Ed/{1D1FAE05-3DAA-4C2E-9BCD-68783FB68A97}.Customer First Name\`d.T.~Ed/ \`d.T.~Ed/{1D1FAE05-3DAA-4C2E-9BCD-68783FB68A97}.Customer Last Name\`d.T.~Ed/" #Remedy Requester Name
$DataBusInput5 = \`d.T.~Ed/{C4144FC2-3F2A-4A65-B7F0-B1E5EA3C9022}.Output text\`d.T.~Ed/ #Pass Date to Disable Account

#-----------------------------------------------------------------------

## Initialize result and trace variables
# $ResultStatus provides basic success/failed indicator
# $ErrorMessage captures any error text generated by script
# $Trace is used to record a running log of actions
$ResultStatus = ""
$ErrorMessage = ""
$Trace = (Get-Date).ToString() + "`t" + "Runbook activity script started" + " `r`n"
       
# Create argument array for passing data bus inputs to the external script session
$argsArray = @()
$argsArray += $DataBusInput0
$argsArray += $DataBusInput1
$argsArray += $DataBusInput2
$argsArray += $DataBusInput3
$argsArray += $DataBusInput4
$argsArray += $DataBusInput5

# Establish an external session (to localhost) to ensure 64bit PowerShell runtime using the latest version of PowerShell installed on the runbook server
# Use this session to perform all work to ensure latest PowerShell features and behavior available
$Session = New-PSSession -ComputerName localhost

# Invoke-Command used to start the script in the external session. Variables returned by script are then stored in the $ReturnArray variable
$ReturnArray = Invoke-Command -Session $Session -Argumentlist $argsArray -ScriptBlock {
    # Define a parameter to accept each data bus input value. Recommend matching names of parameters and data bus input variables above
    Param(
        [ValidateNotNullOrEmpty()]
        [string]$DataBusInput0,
        
        [ValidateNotNullOrEmpty()]
        [string]$DataBusInput1,

        [ValidateNotNullOrEmpty()]
        [string]$DataBusInput2,

        [ValidateNotNullOrEmpty()]
        [string]$DataBusInput3,

        [ValidateNotNullOrEmpty()]
        [string]$DataBusInput4,

        [ValidateNotNullOrEmpty()]
        [string]$DataBusInput5
    )

    # Define function to add entry to trace log variable
    function AppendLog ([string]$Message)
    {
        $script:CurrentAction = $Message
        $script:TraceLog += ((Get-Date).ToString() + "`t" + $Message + " `r`n")
    }

    # Set external session trace and status variables to defaults
    $ResultStatus = ""
    $ErrorMessage = ""
    $script:CurrentAction = ""
    $script:TraceLog = ""

    try 
    {
        # Add startup details to trace log
        AppendLog "Script now executing in external PowerShell version [$($PSVersionTable.PSVersion.ToString())] session in a [$([IntPtr]::Size * 8)] bit process"
        AppendLog "Running as user [$([Environment]::UserDomainName)\$([Environment]::UserName)] on host [$($env:COMPUTERNAME)]"
        AppendLog "Parameter values received: DatabusInput0=[$DataBusInput0]; DataBusInput1=[$DataBusInput1]; DataBusInput2=[$DataBusInput2]; DataBusInput3=[$DataBusInput3]; DataBusInput4=[$DataBusInput4]; DataBusInput5=[$DataBusInput5]"

        # # # # # # # # # # # # # # # # # # #
        # ADVANCE DISABLE USER ACCOUNT... #
        # See AppendLog for Comments              #
        # # # # # # # # # # # # # # # # # # #

            AppendLog "Loading Quest Powershell Module"
        Add-PSSnapin Quest.ActiveRoles.ADManagement
            AppendLog "Module Load Command Completed"
       
            AppendLog "Connecting to ActiveRoles Server $DataBusInput0"
        Connect-QADService -Proxy -Service $DataBusInput0
            AppendLog "ARS Connection Command Completed"
                    
            AppendLog "Setting Expiry on Account $DataBusInput1\$DataBusInput2"
        Set-QADUser "$DataBusInput1\$DataBusInput2" -AccountExpires $DataBusInput5
            AppendLog "Set Expiry Command Completed"

            AppendLog "Adding User to ROLE-G-ScheduledDeprovision $DataBusInput1\$DataBusInput2"
        Set-QADUser "$DataBusInput1\$DataBusInput2" -AccountExpires $DataBusInput5
            AppendLog "Adding to Security Group Command Completed"
        
            AppendLog "Adding Note to $DataBusInput1\$DataBusInput2"
        Set-QADUser "$DataBusInput1\$DataBusInput2" -Notes "Advance Deprov Scheduled Under $DataBusInput3 for $DataBusInput5 (Requested by $DatabusInput4)"
            AppendLog "Adding to Security Group Command Completed"
           
        # Example of custom result value
        $myCustomVariable = "Something I want to publish back to the runbook data bus"

        # Validate results and set return status
        AppendLog "Finished work, determining result"
        $EverythingWorked = $true
        if($EverythingWorked -eq $true)
        {
           $ResultStatus = "Success"
        }
        else
        {
            $ResultStatus = "Failed"
        }
    }
    catch
    {
        # Catch any errors thrown above here, setting the result status and recording the error message to return to the activity for data bus publishing
        $ResultStatus = "Failed"
        $ErrorMessage = $error[0].Exception.Message
        AppendLog "Exception caught during action [$script:CurrentAction]: $ErrorMessage"
    }
    finally
    {
        # Always do whatever is in the finally block. In this case, adding some additional detail about the outcome to the trace log for return
        if($ErrorMessage.Length -gt 0)
        {
            AppendLog "Exiting external session with result [$ResultStatus] and error message [$ErrorMessage]"
        }
        else
        {
            AppendLog "Exiting external session with result [$ResultStatus]"
        }
        
    }

    # Return an array of the results. Additional variables like "myCustomVariable" can be returned by adding them onto the array
    $resultArray = @()
    $resultArray += $ResultStatus
    $resultArray += $ErrorMessage
    $resultArray += $script:TraceLog
    $resultArray += $myCustomVariable
    return  $resultArray  
     
}#End Invoke-Command

# Get the values returned from script session for publishing to data bus
$ResultStatus = $ReturnArray[0]
$ErrorMessage = $ReturnArray[1]
$Trace += $ReturnArray[2]
$MyCustomVariable = $ReturnArray[3]

# Record end of activity script process
$Trace += (Get-Date).ToString() + "`t" + "Script finished" + " `r`n"

# Close the external session
Remove-PSSession $Session